# Generated by Django 6.0.6 on 2026-06-28 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Motocicleta'), ('CAMION', 'Camión'), ('BICICLETA', 'Bicicleta'), ('OTRO', 'Otro')], default='CARRO', max_length=20, verbose_name='Tipo de Vehículo')),
                ('propietario', models.CharField(blank=True, max_length=150, verbose_name='Propietario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='RegistroParqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de Entrada')),
                ('hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('puesto', models.CharField(blank=True, max_length=10, verbose_name='Puesto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('ACTIVO', 'En parqueadero'), ('FINALIZADO', 'Salió')], default='ACTIVO', max_length=15, verbose_name='Estado')),
                ('registrado_por', models.CharField(blank=True, max_length=150, verbose_name='Registrado por')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='parqueadero.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Registro de Parqueadero',
                'verbose_name_plural': 'Registros de Parqueadero',
                'ordering': ['-hora_entrada'],
            },
        ),
    ]
